version: '3.7'
services:
  node_app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'

  mysql_service:
    image: mysql:8.0.26
    ports:
      - '3306:3306'
#    volumes:
#      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=app
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  postgres_service:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
#    volumes:
#      - ./data_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app